# Generated by Django 3.0 on 2019-12-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='users', to='app1.Event'),
        ),
    ]
