# Generated by Django 3.0 on 2019-12-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='gg', upload_to='images/'),
        ),
    ]
