# Generated by Django 3.0 on 2019-12-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20191226_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo',
        ),
    ]
